name: selfcare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  shimmer: ^3.0.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.2
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.2
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
